FROM golang:1.26-alpine

RUN go install github.com/air-verse/air@latest && apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.docker.toml"]
